### PR TITLE
Final General Review of thatSound App

### PR DESCRIPTION
**Pull request by jicamargo**
# 🎵 Final General Review of thatSound App 🎵

### 🚀 Description:
This Pull Request includes the final general review of the thatSound App. The thatSound App is a powerful single-page application (SPA) built with React and Redux that revolutionizes the way users discover, explore, and download sound samples. The app provides a seamless user experience for musicians, producers, and sound enthusiasts by offering a vast collection of high-quality sound samples from various genres and instruments. 🎵

The main pages of the app are 🚀:

1. Home Page: When the page loads, the app displays a list of categories that can be filtered by parameters such as category name. Numeric values per category, retrieved from the chosen API, are also displayed. Clicking on a category item navigates the user to the Details page.

2. Details Page: The Details page retrieves data from the API to show detailed information about the selected category. Clicking the "Back" button (<) navigates the user back to the Home page.

Requirements:

1. API: The app is based on an API that provides numeric values based on parameters. 

2. Design: The app follows design guidelines, including colors, typography, and layout. The original design idea by Nelson Sakwa on Behance is credited in the README file.

3. Interactions:
   - Home Page: Displays categories and numeric values. Clicking on a category item navigates to the Details page.
   - Details Page: Shows detailed data in the selected category. Clicking the "Back" button navigates back to the Home page.

4. Testing: Unit tests are created for pure functions in the Redux code. Integration tests are created using React Testing Library. Mocking API access and Redux Store connection may be required.

5. Technical:
   - The app is a single-page application (SPA) built with React and Redux.
   - Data retrieved from the API is stored in the Redux store.
   - Filtering of API data is implemented using a Filter stateless component.
   - Each page has a unique route within the SPA.
   - The app is deployed and accessible online using Netlify

6. Documentation: A video is recorded in Loom (and Added to README) to present the features of the project. The video includes a description of the project, a demo of the project features, and highlights of interesting code or accomplishments.

Please review this Pull Request to ensure all requirements are met. 💯 
Thank you 👍🏼

### CODE REVIEW

**Review by iambenkis — COMMENTED** [review]
Hi @jicamargo  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that is beautifully made however you did not have  all the header in your README file , Kindly check the [README](https://github.com/microverseinc/readme-template) template and make sure all relevant headers and section are found in your README file 👍  


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @iambenkis in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jicamargo** [comment]
Thank you @iambenkis I will update Readme and submit again.

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:✔️✔️✔️

Hi @jicamargo ✔️✔️✔️✔️✔️

Your project is complete! Great job  🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍✔️✔️✔️
- Descriptive Pull Request✔️
- Correct gitflow✔️
- components and API tested✔️
- professional readme✔️
- well deployed and demo ✔️ 
- No linter errors✔️

video presentation
--- Great job for being audible throughout the presentation. Please always ensure you introduce yourself and the purpose of why you chose to build what you built and how it can benefit the user.
--- Nice job taking your time to demonstrate how the app work and the reason for the selected design, please always go the extra mile to show your code base and what you feel proud of building.


<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

fff

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jicamargo** [comment]
Thank you @tufoinnkuo10 👍💪

**Pull request merged**
